# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://toddr.org'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Todd Rylaarsdam
# Description of the Site
description: A JavaScript/NodeJS Developer and Embedded Systems Engineer
# URL of Image of the Site
site-image: https://cdn.toddr.org/assets/images/t-logo.png
# Keywords of the Site
site-keywords: Todd, Rylaarsdam, JavaScript, Canvas, CPU, Emulator
# URL for the Image of custom Favicon
favicon-url: https://cdn.toddr.org/assets/images/t-logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/7135028/pexels-photo-7135028.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: todd@toddr.org
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  trylaarsdam
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-TEPR3PN200

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Todd Rylaarsdam
# URL for the Image of the Author
author-image: https://cdn.toddr.org/assets/images/t-logo.png
# 60 Words About the Author
author-about: <b>About Me</b><br/><br/>I've been a software development and embedded systems engineering intern at Windy City Lab for the last 1.5 yrs. Most of my personal work is available on GitHub <a href="https://github.com/trylaarsdam">@trylaarsdam</a>. For software development, I have experience making apps and backends with JavaScript and Node.JS, Python, and C++. I work regularly with tools like Express.JS, Mocha.JS, Pug, Firestore, Mongo, and Electron for web apps and backends, and utilize both microcontrollers and their software suites from Particle, Arduino, and ST with their STM32 line. For hardware work, I primarily use KiCad to design schematics and PCBs to more tightly integrate products and ideas, and turn prototypes into production hardware. I run Windows on my main workstation, but also work with MacOS regularly. I have experience managing, configuring, securing, and deploying code to servers running Linux (specifically debian-based distros). I've also used tools like PM2, Docker, and GitHub Actions to automate and streamline these workflows as well.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "projects/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
