# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://toddr.org'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Todd Rylaarsdam
# Description of the Site
description: Full stack developer
# URL of Image of the Site
site-image: https://toddr.org/assets/images/t-logo.png
# Keywords of the Site
site-keywords: Todd, Rylaarsdam, JavaScript, Canvas, CPU, Emulator
# URL for the Image of custom Favicon
favicon-url: https://toddr.org/assets/images/t-logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/7135028/pexels-photo-7135028.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: todd@toddr.org
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: todd-rylaarsdam-0b3462234
github_username:  trylaarsdam
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-Q6FFZ6PFFV

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Todd Rylaarsdam
# URL for the Image of the Author
author-image: https://toddr.org/assets/images/t-logo.png
# 60 Words About the Author
author-about: <b>About Me</b><br/><br/>I'm currently a student at George Fox University studying computer engineering. Before that I worked as a embeded software development and hardware engineering intern at Windy City Lab. Most of my personal work is available on GitHub <a href="https://github.com/trylaarsdam">@trylaarsdam</a>, and you can read some more about projects I've worked on on the <a href="/projects">projects page</a>. <br/><br/>For software development, I have experience making apps and backends with JavaScript and Node.JS, Swift, Python, and C++. I work regularly with tools like Express.JS, Vue.JS, Firestore, InfluxDB, and Grafana for web apps and backends, and utilize both microcontrollers and their software suites from Particle, Arduino, and ST with their STM32 line for embedded projects.<br/><br/> For hardware work, I primarily use KiCad to design schematics and PCBs to more tightly integrate products and ideas, and turn prototypes into production hardware. I run Windows on my main workstation, MacOS on my laptop, Unraid on my home server, and usually utilize debian-based linux distros for server work. <br/><br/>I also have experience configuring, securing, and deploying code to servers running Linux, and have used tools like PM2, Docker, and GitHub Actions to automate and streamline deployment and testing workflows. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "projects/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
